// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnR56pzyst4OFVi2Dpu6c5qc9mapxnWoM',
    appId: '1:441954248265:web:35d99c0721c2044f0c8198',
    messagingSenderId: '441954248265',
    projectId: 'library-management-system-1425',
    authDomain: 'library-management-system-1425.firebaseapp.com',
    storageBucket: 'library-management-system-1425.firebasestorage.app',
    measurementId: 'G-VF2W82NTHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIu1VFhMnaCJe_AITltkKXY5kUTSvPZmw',
    appId: '1:441954248265:android:fabed8e817b4665a0c8198',
    messagingSenderId: '441954248265',
    projectId: 'library-management-system-1425',
    storageBucket: 'library-management-system-1425.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB65k1X-836b-vpT0dhEOuti6Btb6CAldI',
    appId: '1:441954248265:ios:c995216fd95520d80c8198',
    messagingSenderId: '441954248265',
    projectId: 'library-management-system-1425',
    storageBucket: 'library-management-system-1425.firebasestorage.app',
    iosClientId: '441954248265-ptrec69q0cld406hqbsoga4apii30slf.apps.googleusercontent.com',
    iosBundleId: 'com.example.libraryManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB65k1X-836b-vpT0dhEOuti6Btb6CAldI',
    appId: '1:441954248265:ios:c995216fd95520d80c8198',
    messagingSenderId: '441954248265',
    projectId: 'library-management-system-1425',
    storageBucket: 'library-management-system-1425.firebasestorage.app',
    iosClientId: '441954248265-ptrec69q0cld406hqbsoga4apii30slf.apps.googleusercontent.com',
    iosBundleId: 'com.example.libraryManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnR56pzyst4OFVi2Dpu6c5qc9mapxnWoM',
    appId: '1:441954248265:web:36e5de84ccac7e6f0c8198',
    messagingSenderId: '441954248265',
    projectId: 'library-management-system-1425',
    authDomain: 'library-management-system-1425.firebaseapp.com',
    storageBucket: 'library-management-system-1425.firebasestorage.app',
    measurementId: 'G-N2ZQJGN002',
  );

}